# Generated by Django 4.2.6 on 2024-09-02 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='sensorId',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='equipment.sensor', verbose_name='Sensor asociado'),
        ),
    ]
