# Generated by Django 4.2.6 on 2024-09-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'ordering': ['-equipmentId'], 'verbose_name': 'Lecturas', 'verbose_name_plural': 'Lecturas'},
        ),
    ]
