# Generated by Django 4.2.6 on 2024-08-15 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de fallta')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de anomalía',
                'verbose_name_plural': 'Tipo de anomalía',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('key', models.CharField(max_length=100, verbose_name='Id del grupo')),
            ],
            options={
                'verbose_name': 'Grupos de notificaciones',
                'verbose_name_plural': 'Grupos de notificaciones',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='GroupEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100, verbose_name='Identificador de la anomalía')),
                ('failuteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usergroup.failuretype', verbose_name='Tipo de anomalía')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usergroup.group', verbose_name='Grupo')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Grupos de usuarios',
                'verbose_name_plural': 'Grupos de usuarios',
                'ordering': ['-groupId'],
            },
        ),
    ]
